### ISSUE TITLE
Error on Migration from Django 1.6.x to 1.8.x

### ISSUE THREAD

**Issue by bobtiki** [dstegelman/django-downtime#35]
I had django-downtime installed on a site running Django 1.6.11, and am in the progress of migrating to Django 1.8.3. As part of this, I am moving from South 1.0 to the built-in Django migrations, and Django seems to be freaking out a bit when running the first `makemigrations`. I'm getting this error:

`django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: downtime`

How can I work around this? My first thought is that I'm running in a virtualenv, so there shouldn't be any duplicates, but maybe that's not what this means.

django-downtime is installed via pip, and I realized while deleting the old South migrations for my project's apps that since there was a South migration to install django-downtime, that the numbered South migration file should have been created, and it must live *somewhere,* but for the life of me, I can't figure out where it lives! I have a mild suspicion that's the culprit here (anddeleting that migration file might help), but any ideas would be appreciated, as my test site is basically dead until I can fix this.

Thanks!

The complete trace:

```
(testoptical)[bobtiki@web458 cinedex]$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/bobtiki/.virtualenvs/testoptical/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/bobtiki/.virtualenvs/testoptical/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/bobtiki/.virtualenvs/testoptical/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/bobtiki/.virtualenvs/testoptical/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/bobtiki/.virtualenvs/testoptical/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 125, in handle
    migration_name=self.migration_name,
  File "/home/bobtiki/.virtualenvs/testoptical/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 43, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/home/bobtiki/.virtualenvs/testoptical/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 110, in _detect_changes
    self.old_apps = self.from_state.concrete_apps
  File "/home/bobtiki/.virtualenvs/testoptical/lib/python2.7/site-packages/django/db/migrations/state.py", line 170, in concrete_apps
    self.apps = StateApps(self.real_apps, self.models, ignore_swappable=True)
  File "/home/bobtiki/.virtualenvs/testoptical/lib/python2.7/site-packages/django/db/migrations/state.py", line 230, in __init__
    super(StateApps, self).__init__(app_configs)
  File "/home/bobtiki/.virtualenvs/testoptical/lib/python2.7/site-packages/django/apps/registry.py", line 56, in __init__
    self.populate(installed_apps)
  File "/home/bobtiki/.virtualenvs/testoptical/lib/python2.7/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: downtime
```

**Comment by bobtiki** [comment]
Okay — whew! I think I found it. My GUI FTP app wasn't showing it to me for some reason (until I refreshed the listing), but a little `grep` found it for me in  `/home/bobtiki/.virtualenvs/testoptical/lib/python2.7/site-packages/downtime/migrations`.

Sorry for the false alarm, but perhaps this will be useful to someone else.

**Comment by dstegelman** [comment]
Glad you got it figured out!
